#!/bin/sh
##XXX was PPGDATA=$HOME/pg_/data/db/ ; but that is not where the test is running
PGDATA=pg_/data/db/
PGPORT=7777
export PGDATA
export PGPORT
# start server
pg_/bin/pg_ctl start -o '-c autovacuum=false'
# wait for server to start
sleep 10

# create test db
pg_/bin/createdb pgbench

# set up tables
case $1 in
        "BUFFER_TEST")
                SCALING_FACTOR=`echo "$SYS_MEMORY * 0.003" | bc`
        ;;
        "MOSTLY_CACHE")
                SCALING_FACTOR=`echo "$SYS_MEMORY * 0.2" | bc`
        ;;
        "ON_DISK")
                SCALING_FACTOR=`echo "$SYS_MEMORY * 0.8" | bc`
        ;;
esac

pg_/bin/pgbench -i -s $SCALING_FACTOR pgbench

case $2 in
        "SINGLE_THREAD")
                PGBENCH_ARGS="-c 1"
        ;;
        "NORMAL_LOAD")
                PGBENCH_ARGS="-j $NUM_CPU_CORES -c $(($NUM_CPU_CORES*4))"
        ;;
        "HEAVY_CONTENTION")
                PGBENCH_ARGS="-j $(($NUM_CPU_CORES*2)) -c $(($NUM_CPU_CORES*16))"
        ;;
esac

case $3 in
        "READ_WRITE")
                PGBENCH_MORE_ARGS=""
        ;;
        "READ_ONLY")
                PGBENCH_MORE_ARGS="-S"
        ;;
esac

# run the test 
pg_/bin/pgbench $PGBENCH_ARGS $PGBENCH_MORE_ARGS -T 60 pgbench >$LOG_FILE 2>&1
# drop test db
pg_/bin/dropdb pgbench
# stop server
pg_/bin/pg_ctl stop
